### ISSUE TITLE
Can’t solve ofxLaunchControlXL’s linker error

### ISSUE THREAD

**Issue by AnasGhrab** [2bbb/ofxLaunchControlXL#3]
Hi,

I fact I have the same error as here : https://forum.openframeworks.cc/t/cant-solve-ofxlaunchcontrolxls-linker-error/22249.

As I say there, I made a new project with the projectGenerator and brought sections from the example (which has everything inside the file main.cpp).

I get this :
```
duplicate symbol __ZN18ofxLaunchControlXL16defaultXMLbase64E in:
    /Users/anas/Library/Developer/Xcode/DerivedData/testLCXL-gwwhewdxmlndxzdpcnqzwnrmgona/Build/Intermediates/testLCXL.build/Debug/testLCXL.build/Objects-normal/x86_64/main.o
    /Users/anas/Library/Developer/Xcode/DerivedData/testLCXL-gwwhewdxmlndxzdpcnqzwnrmgona/Build/Intermediates/testLCXL.build/Debug/testLCXL.build/Objects-normal/x86_64/ofApp.o
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by 2bbb** [comment]
@AnasGhrab 

ahhhh...

oh yeah.

i'll fix it!

thanks!!

**Comment by 2bbb** [comment]
@AnasGhrab 
maybe current master was fixed.
please check it!

thanks!

**Comment by AnasGhrab** [comment]
Yes, it's ok now ;)

**Comment by 2bbb** [comment]
@AnasGhrab 

thanks for checking!
