### ISSUE TITLE
Does not compile on linux

### ISSUE THREAD

**Issue by edap** [2bbb/ofxLaunchControlXL#6]
![screenshot from 2019-02-07 18-25-20](https://user-images.githubusercontent.com/161152/52430182-d6cb7680-2b05-11e9-8189-0cb21e099585.png)

**Comment by 2bbb** [comment]
@edap 
maybe you need to add `ofxPoco`.

**Comment by edap** [comment]
yes that was the problem. Maybe it make sense to add ofxPoco to the list of dependencies in the readme file. Thanks ;)

**Comment by 2bbb** [comment]
@edap 

yes! README was updated!
